# file: .travis.yml
language: objective-c

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N


script:

- xctool clean build -project "MIDIPlayer.xcodeproj" -scheme "MIDIPlayer"  | xcpretty -c
- xctool test -project "MIDIPlayer.xcodeproj" -scheme "MIDIPlayer"  | xcpretty -c


# http://docs.travis-ci.com/user/languages/objective-c/


